#!/usr/bin/env python

import json
import os
import sys


with open(sys.argv[1]) as f:
    schema = json.load(f)

schema['graph_subscription_callback_url'] = os.path.expandvars(schema['graph_subscription_callback_url'])

with open(sys.argv[1], 'w') as f:
    f.write(json.dumps(schema, indent=2, sort_keys=True))
