---

- connection: local
  gather_facts: yes
  hosts: all
  tasks:
    - import_role:
        name: mako-ai.facebook-messenger

    # https://devcenter.heroku.com/articles/platform-api-reference#config-vars-update
    - name: Write application-specific variables to Heroku config vars
      uri:
        body: |
          {
            "ACCESS_TOKEN": "{{ user.access_token }}",
            "FACEBOOK_USER_ID": "{{ user.id }}"
          }
        body_format: json
        headers:
          Accept: application/vnd.heroku+json; version=3
          Authorization: Bearer {{ ansible_env.HEROKU_API_KEY }}
          Content-Type: application/json
        method: PATCH
        return_content: yes
        url: https://api.heroku.com/apps/{{ ansible_env.HEROKU_APP_NAME }}/config-vars
